version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-app-network

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
    networks:
      - my-app-network
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - my-app-network
    ports:
      - "3000:5173"  # Adjust as necessary

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-app-network
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
networks:
  my-app-network:
    external: true